#!/usr/bin/env python
"""Re-sync the skill kit from the built deck. Run after every structural or CSS edit.

  python sync_kit.py deck/index.html [--check]

The kit holds two copies of the deck so a later project can fork it:
  references/design_system.css   the deck's <style> block, with the kit header on top
  references/engine_skeleton.html the whole deck with the __DATA__ blob emptied

Both used to be regenerated by ad-hoc python snippets, which is how they drifted. --check exits
non-zero when either file is stale (use it before handover); without it the files are rewritten.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(os.path.dirname(HERE), "references")
CSS = os.path.join(REF, "design_system.css")
SKEL = os.path.join(REF, "engine_skeleton.html")
EMPTY = '{"images":{},"annotations":{},"facts":{}}'
HEADER = """/* ============================================================================
   Gym mood board deck: design system (light warm ground)
   Tokens + scaffold (fixed stage, scrolling cards, chapters) + components for the three
   layer types: none (plain ground), figure (renders and plans with numbered boxes), grid (tiles).
   The skeleton inlines a copy of this file; when you change a token here, change
   it in the deck too. Principles: references/design.md.
   Generated by scripts/sync_kit.py from deck/index.html: edit the deck, then re-run it.
   ========================================================================== */

"""
INLINE_NOTE = re.compile(r"^/\* Inlined copy of .*?\*/\n", re.S)


def build(html):
    m = re.search(r"<style\b[^>]*>(.*?)</style>", html, re.S | re.I)
    if not m:
        sys.exit("no <style> block in the deck")
    css = HEADER + INLINE_NOTE.sub("", m.group(1).strip("\n")) + "\n"
    skel, n = re.subn(r"(/\*__DATA__\*/).*?(/\*__END__\*/)", lambda _: "/*__DATA__*/" + EMPTY + "/*__END__*/",
                      html, flags=re.S)
    if n != 1:
        sys.exit("expected the __DATA__ markers exactly once, found %d" % n)
    return css, skel


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("deck", nargs="?", default="deck/index.html")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    css, skel = build(open(a.deck, encoding="utf-8").read())
    stale = []
    for path, text in ((CSS, css), (SKEL, skel)):
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == text:
            continue
        stale.append(os.path.relpath(path))
        if not a.check:
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(text)
    if a.check:
        print(("FAIL: stale, re-run sync_kit.py: " + ", ".join(stale)) if stale else "ok: kit matches the deck")
        return 1 if stale else 0
    print(("ok: rewrote " + ", ".join(stale)) if stale else "ok: kit already matched the deck")
    return 0


if __name__ == "__main__":
    sys.exit(main())
